### ISSUE TITLE
/documents API endpoint should return document pk

### ISSUE THREAD

**Issue by pycal** [mayan-edms/mayan-edms#194]
It would be helpful to have the document pk returned with the response object so that tags and metadata can be applied after a new document is POSTed

**Comment by pycal** [comment]
As far as I can tell this is supposed to happen, but I'm noticing two problems:

The file in question is: apps/documents/api_views.py

1. task_new_document.apply_async does not add the shared_uploaded_file_id to response.content
2. shared_uploaded_file.id (and shared_uploaded_file.pk) == document.id + 2

**Comment by rosarior** [comment]
To insert the document id we need access to the response. This is not guaranteed because the actual code to take the uploaded file and turn it into a Mayan document might not be running on the same computer that received the POST request.

The actual document entry in the model would need to be created by the process getting the request before launching the celery task to finish the rest of the process: file MIME types guessing, file format introspection, page count, signature verification, unlike OCR these need to happen as the document is being uploaded. If the celery task fails or is interrupted we end up with a shell/invalid document that has no document_versions and no content. To avoid this, the entire process is enclosed in a database transaction: https://github.com/mayan-edms/mayan-edms/blob/master/mayan/apps/documents/managers.py#L62

shared_upload_file.id and document.id are also not guaranteed (not even meant) to correlate. In an installation with 2 frontend nodes using NGINX load balancing and 2 worker nodes running celery, share_upload_file.id and document.id disassociate as soon as 3 documents of different sizes (and processing times) are uploaded.

I agree that returning the document id at creation should be the norm, but I don't see a way to make that happen without risking corrupting the database in the event of post POST request interruption.

**Comment by pycal** [comment]
That clarifies a lot, thanks Roberto.

So am I correct in assuming that it is only appropriate to trust a successfully executed celery worker process?

Can we leverage a promise from the celery worker which conducts the database transaction? If so that's a workable solution which will allow us to include the document.id as well as other useful data (thinking HATEOAS ie http://localhost:8000/api/v0tags/document/{document_pk}/tags/{pk}/ )

Is that a feasible approach?

**Comment by rosarior** [comment]
No problem :)

Trusting the celery worker is the only thing that can be done for now. The closest things to a celery promise I can think of is returning the celery task number and provide an API endpoint to check the status of the task, this way we will know when the document is ready. There is a ticket (gh-issue #169) to add a task viewer, adding an API to it should solve this. 

Until the document is finished processing the transaction is not committed and the document instance in progress cannot be made to relate to anything yet.

I'm not familiar with HATEOAS but there is already an endpoint to check the tags of a document, attach and remove them:

![screenshot from 2015-06-08 18 13 48](https://cloud.githubusercontent.com/assets/413955/8046582/280aac72-0e0a-11e5-92c1-4c1d14393e28.png)

There is not way to attach a tag to a document at the same time it is being uploaded, the **sources** and/or **documents** app would need to have knowledge about **tags**. 

Is this what you meant?

**Comment by rosarior** [comment]
Never mind the last lines, I see what you mean. You want to upload a document and have the document id returned so you know to which document apply a tag without having to use the search to find the document, which makes sense if you want to auto tag uploaded documents from an API!

I see your predicament...

An empty Document instance would need to be created to be able to be able to return the PK at least and have the model manager ignore empty Documents to they don't appear in the list of documents while the celery task finishes processing.

**Comment by rosarior** [comment]
Just thought of another possibility, a new API endpoint identical to POST to /api/v0/documents/documents but that waits for the tasks to finish so it can return the document ID. POST /api/v0/documents/documents/block or something similar. Would that help?

**Comment by pycal** [comment]
Yep you got it, the goal is definitely to be able to apply tags to newly uploaded documents without having to do an additional lookup.

From the standpoint of the API consumer it seems clearest and fastest to include all of the data available for a new document, as it will save time from making additional http requests; in my case the number of requests I have to make is really important as each additional second I spend to migrate a document increases my total migration time by two days!

Here's an example of a request I'd like to be able to make:
```
endpoint = 'https://localhost/api/v0/documents/documents/?format=json'
path = '/Volumes/MIGRATE/hi-res/000/woman-driving.jpg'
f = open(path, 'rb')
file = {'file': f}
mime = magic.from_file(path, mime=True)
headers = {'content-type': mime}

payload = {
	'document_type': '3',
	'metadata': {
		'industry': 'automotive'
	}
	'tags': ['blue car', 'driving', 'city', 'urban']
	'document_language': 'eng'
	'document_description': 'this is a photo of a woman driving a blue car in the city'
}

return requests.post(endpoint, auth=HTTPBasicAuth('admin', 'password'), data=payload, files=file, verify=False, headers=headers)
```

It sounds like a blocking endpoint would satisfy my requirement but I'm concerned I'll run in to request timeouts, and also that my total migration time will be very high.

**Comment by pycal** [comment]
That said it sounds like the bar to try that is low while this other approach is more complicated, so I'm willing to test it out and report back performance!

**Comment by pycal** [comment]
Another thing that would make the latter approach more manageable is being able to POST all the tags I want to apply to a document id simultaneously; I have an average of 20 tags per document, and currently I'd need to make one request per tag.
