### ISSUE TITLE
Large Documents Processing

### ISSUE THREAD

**Issue by sochix** [mayan-edms/mayan-edms#248]
Hello! 
What is the largest document size your EDMS can process?
I submitted 30 Mb csv file and it hang up.

**Comment by rosarior** [comment]
Hi,
where did you submit the file? Demo install, test install, production install, Docker install or VM install?
Is the document well formed? Can you make it available? If not, can you provide a sample document with the same properties?

**Comment by sochix** [comment]
@rosarior I installed Mayan via Docker image. The document is well-formed csv file which can be opened with Excel or notepad. The document size is 40 Mb. 

Can't find a way to upload it to GitHub :(

**Comment by rosarior** [comment]
There is no hard coded file size limit, the maximum size file that can be processed will be determined by the hardware running Mayan. Here is an example of a live [60 page document](http://demo.mayan-edms.com/documents/211/preview/), a [77 page document](http://demo.mayan-edms.com/documents/210/preview/), and a  [1198 page document](http://demo.mayan-edms.com/documents/213/preview/), all browseable, full text searchable, and with multilingual OCR performed. 

Performance is also important, here is a video of Mayan uploading and processing 500 documents in 9 seconds on a 4 year old, dual core laptop: https://www.youtube.com/watch?v=HBiaBm5ZCz0
Cloud installs are much faster.

Another example with a custom UI holding 60599 documents:
![screenshot from 2017-02-21 03-17-07](https://cloud.githubusercontent.com/assets/413955/23154561/e2e4a9ba-f7e4-11e6-935b-a837f89e2367.png)

As you can see a lot of work has gone into making sure it can process and scale to any size.

Can you expand on your description of "it hang up"? The program crashed with an error? Or it froze due to the host computer running out of memory?

If your system is running out of resources, Mayan supports cluster deployments, on local or cloud clusters and it will scale to use all available resources. If you are unfamiliar with cluster installs some tools for orchestration are available to deploy Mayan using Salt Stack, Ansible, and Fabric: http://www.mayan-edms.com/ecosystem/
In addition to those we are working to release a Packer setup and a Terraform recipe.

Please compress the file, uploading to a 3rd party file sharing service like Dropbox and share the link if the content of the file is not private, and we'll test it to make sure it is not a bug in the software.

Thanks

**Comment by sochix** [comment]
Thank you for your answer. To help you investigate the issue I uploaded file to https://www.dropbox.com/s/3kexeiu9kcwxoh0/Officers.csv?dl=0 .

**Comment by yaindex** [comment]
@rosarior The OP of this issue is the creator of a competing paperless product that sells for 990$ with a fraction of the features of Mayan DMS. Their project is commercial-close-sourced and they are trying to bend the rules trying to have it posted on open source lists to gain traction, see this ticket -> https://github.com/Kickball/awesome-selfhosted/pull/966 or their github page for the project. Read their blog to see how they talk negatively about Mayan DMS: http://blog.rdseventeen.com/going-paperless-cloud-archive-for-all-your-documents/ and you'll see my point.
