### ISSUE TITLE
Create cabinet fails on Oracle

### ISSUE THREAD

**Issue by simeon-walker** [mayan-edms/mayan-edms#258]
The query in mayan/apps/cabinets/models.py line 66:

`if Cabinet.objects.select_for_update().filter(parent=self.parent, label=self.label).exists():`

fails to build valid SQL for Oracle due to the `select_for_update()` giving

`DatabaseError: ORA-00907: missing right parenthesis`

Remove the  `select_for_update()` does allow the cabinet to be created but I'm not sure what the side effects might be.

**Comment by rosarior** [comment]
The select_for_update is meant to lock the database to avoid race conditions. It is being used here (https://gitlab.com/mayan-edms/mayan-edms/blob/master/mayan/apps/cabinets/models.py#L66), due to an issue in Django (https://code.djangoproject.com/ticket/1751) which cause the uniqueness check to fail in some cases allowing duplicated values. In this context it is used to avoid a parent cabinet to have child cabinets with the same label. The select_for_update is to avoid two concurrent users using the same label. If your deployment user concurrency is not high your can remove the line without causing trouble. However, the fact that Oracle returns an error means this could be an upstream issue.

**Comment by rosarior** [comment]
Another issue with select_for_update when using Oracle, this time in Celery (https://github.com/celery/kombu/issues/472).

**Comment by rosarior** [comment]
Seems to be a long standing issue with Django's SQL compiler for Oracle (http://python.6.x6.nabble.com/Django-23061-Oracle-SQL-compiler-adding-outer-pagination-selects-causing-ORA-00907-missing-right-par-td5064532.html). The workaround would be to add Oracle detection and disable select_for_update until this get's fixed. 

Is there a Docker image available for Oracle? I would like to add it to the test suit to avoid these.

**Comment by rosarior** [comment]
select_for_update is now disabled when then backend is Oracle. 
Also a test target was added to launch an Oracle 11xe container and run all the tests on it (https://github.com/mayan-edms/mayan-edms/blob/master/Makefile#L127). Use:

    make test-oracle-all

or

    make test-oracle MODULE=documents

to test individual apps or modules.
