### ISSUE TITLE
Shared doment links accessible from outside

### ISSUE THREAD

**Issue by Chluz** [mayan-edms/mayan-edms#262]
Hi, this 'issue' is actually a feature request
I was wondering if it would be possible for outside users to be able to access the links provided by Mayan when using the email link action. 

The email link action would then have a tickbox for 'Allow outside access to document' and the option of putting a password. When ticked, the document would be accessible without loging in to Mayan. 

Personally I would love it if it could interface with nextcloud, perhaps by using the [https://github.com/cghdev/cloud-dl](https://github.com/cghdev/cloud-dl ) bash scripts (which actually need an update, I need to log a pull request). Nextcloud actually already has all the require infrastructure for it, so I can see myself creating a Mayan user in nextcloud, and having mayan push the documents to nextcloud before requesting a share link from nextcloud. 

I understand that this is not a small request though :) but this would make use of one of the advantages of having a server hosted EDMS system!
I can probably build a POC using nextcloud and cloud-dl if need be. 

Thanks in advance, really loving Mayan up until now !

**Comment by rosarior** [comment]
Hi,

Mayan actually has this a long time ago, it's how the State of California publishing public documents (https://cpucadviceletters.org/documents/list/recent/). But when Mayan moved to a role-based access control system, this had to be removed.

There is desire to add it again but that means changes in the new authentication and permissions systems, as well as changes in the view's permission checking, because in effect this feature would be bypassing all that. Instead of hardcoding or bypassing, I would prefer to implement this as a feature of those systems. As such aside for the anonymous roles, most of the implementation details are still missing.

The issue tracking it is #220 on GitLab (https://gitlab.com/mayan-edms/mayan-edms/issues/220) and the tentative name is "Portals". I'll add more details on what is missing/required to get this implemented to see if someone helps figuring out the solutions.

I don't get all the interaction with nextcloud, can you expand on that a bit?

No worries, almost nothing in Mayan is small or simple :) 

Thanks for giving Mayan a try and for the issues/requests.

**Comment by Chluz** [comment]
Hi Rosarior, 

Great hat you already have this in your sights. 

Nextcloud integration is only to avoid you having to code complicated permissions and a sharing system.
From the point where you share a document externally, you could trigger the nextcloud api to:
- upload the document to a specific nextcloud account (specifically created for mayan)
- trigger a nextcloud share for the document, with or without password and return the link and password
- set an expiry date if required
- nextcloud would return the link URL and password to mayan, which sends the email. 

You only need to write a few lines of python for the api calls, but then you also have to figure out a way of managing the files which have been uploaded to nextcloud, probably with a "shared documents" table. you can then use that table to query the nextcloud api to unshare and delete a specific document.

Of course doing everything in Mayan natively would be much cleaner; nextcloud is pretty much a hack :)
