### ISSUE TITLE
Make it possible to link documents together

### ISSUE THREAD

**Issue by plotti** [mayan-edms/mayan-edms#267]
Often I have the problem that I have scanned in a contract, which is consisting of multiple pages when i scan them. They then via import get turned into multiple documents. I would love to merge them back together into one somehow, but don't have any means todo so. Could we have a feature, maybe in the dropdown saying <merge documents> and then all the pages of one are added to the other one or so. 

I know there are smart links in combination with metadata, and it works when i have a metadata property e.g. collection where i enter an arbitrary name that links the two documents. But this is really cumbersome when adding this property and also when retrieving documents matching it.

**Comment by rosarior** [comment]
The idea has been discussed before and we named it "Document merging". The main feature blocker is finding a way to be able to undo the merge in a way that works with how Mayan keeps document versions. Since Mayan is used in legal settings, it must preserve the chain of custody of a document. What remains is a way to merge not only the documents' pages but also their internal history. If this problem is solved document merging (and document splitting) can be added.

**Comment by plotti** [comment]
I thought of another idea: Under the versioning feature, why can't I chose another document as the new version of this document? Right now i can only upload files. Even adding them from the scanner is not available. Is that so by design?
